### ISSUE TITLE
Entity Schema validate 정합성 일치

### ISSUE THREAD

**Issue by Choi-JJunho** [BCSDLab/KOIN_API_V2#359]
# 어떤 이슈인가요?
현재 스키마와 엔티티가 정확하게 일치하지 않아 validate를 통과하지 못하고있음.
```yaml
spring
  jpa:
    hibernate:
      ddl-auto: validate
```
